# Generated by Django 6.0.1 on 2026-01-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_id",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="ID чата в Telegram"
            ),
        ),
    ]
