# Generated by Django 6.0.1 on 2026-01-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_telegram_id"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AlterField(
            model_name="user",
            name="telegram_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=20,
                null=True,
                verbose_name="ID чата в Telegram",
            ),
        ),
    ]
